#include <stdio.h>
#include <stdlib.h>
#include "ast.h"  // Include the abstract syntax tree header

// Function declarations from other components
int yyparse(void);              // Function generated by Bison
extern ASTNode* root;           // Root of the AST, defined in the parser
extern FILE* yyin;              // Input stream for Flex

void analyze_node(ASTNode* node);  // Semantic analysis function
void generate_code(ASTNode* node); // Code generation function

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <source_file>\n", argv[0]);
        return EXIT_FAILURE;
    }

    FILE *fp = fopen(argv[1], "r");
    if (!fp) {
        perror("Error opening file");
        return EXIT_FAILURE;
    }

    // Set Flex to read from the file instead of standard input
    yyin = fp;

    // Parse the input file
    if (yyparse() != 0) {
        fprintf(stderr, "Parsing failed!\n");
        return EXIT_FAILURE;
    }

    fclose(fp);  // Close the source file

    // Perform semantic analysis on the AST
    if (root) {
        analyze_node(root);
    } else {
        fprintf(stderr, "No syntax tree to analyze\n");
        return EXIT_FAILURE;
    }

    // Generate code from the AST
    printf("\nGenerated Code:\n");
    if (root) {
        generate_code(root);
    } else {
        fprintf(stderr, "No syntax tree to generate code from\n");
        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
